# Generated by Django 2.1.4 on 2019-01-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('Cur_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Cur_Abbreviation', models.CharField(default='000', max_length=3)),
                ('Cur_Scale', models.IntegerField(default=1)),
                ('Cur_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Valuta_kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Cur_OfficialRate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('Cur_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_exrate.Valuta')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_exrate.Question'),
        ),
    ]
