# Generated by Django 2.1.4 on 2018-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_exrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cur_ID', models.IntegerField()),
                ('Date', models.DateTimeField(verbose_name='Date rate')),
                ('Cur_Abbreviation', models.CharField(max_length=3)),
                ('Cur_Scale', models.IntegerField(default=1)),
                ('Cur_Name', models.CharField(max_length=200)),
                ('Cur_OfficialRate', models.IntegerField()),
            ],
        ),
    ]
