# Generated by Django 2.1.4 on 2019-01-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_exrate', '0002_valuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta_kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='Date rate')),
                ('Cur_Abbreviation', models.CharField(max_length=3)),
                ('Cur_Scale', models.IntegerField(default=1)),
                ('Cur_Name', models.CharField(max_length=200)),
                ('Cur_OfficialRate', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='Cur_Abbreviation',
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='Cur_Name',
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='Cur_OfficialRate',
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='Cur_Scale',
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='Date',
        ),
        migrations.AddField(
            model_name='valuta_kurs',
            name='Cur_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_exrate.Valuta'),
        ),
    ]
