# Generated by Django 2.1.4 on 2019-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_exrate', '0004_auto_20190104_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuta_kurs',
            name='Cur_OfficialRate',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
